### ISSUE TITLE
Problem with login in

### ISSUE THREAD

**Issue by magtimmermans** [kaylathedev/life360-node-api#5]
Hi,

First of all thanks for this API. I hope it is still working as I really love to use it. I have a problem with login. I can access via my app (Same credentials (email/pw) ) login. But when I use the code I get a 403 (Access forbidden)?

```
start session
Error: Server responded with a 403, Forbidden
    at IncomingMessage.<anonymous> (/node_modules/life360-node-api/index.js:1150:27)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)

```

It seems that at least the URL is changed (they did go to the cloud). https://api-cloudfront.life360.com/v3/oauth2/token

**Comment by rjhornsby** [comment]
I'm hitting the same problem. Can't remember where I read it, but recently came across a discussion that L360 had intentionally killed the API. It was always unofficial and unsupported. They just made it so only their app could access the service.

It might be possible to re-reverse engineer the protocol, but with no promises and actively working against us to keep us out, we're left with a game of cat and mouse with L360.

**Comment by 3nt3** [comment]
It works for me, so maybe you could try to reproduce it again? @rjhornsby @magtimmermans

**Comment by csmit195** [comment]
Same in 2025.
